name: personality_scanner
description: AI Personality Analysis from Photos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.3
  image_picker: ^1.0.4
  http: ^1.1.0
  path_provider: ^2.0.15
  share_plus: ^7.0.2
  path: ^1.8.3
  dio: ^5.3.2
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true